name: dpg

channels:
  - defaults

dependencies:
  - python=3.7
  - matplotlib=3
  - notebook=5.7
  - numpy=1.17
  - pandas=0.25
  - scikit-learn=0.21
  - scipy=1.2
  - ipywidgets
  - pytables=3.5
  - pip
  - pillow
  - tqdm
